#import "_Users_bstern_Documents_code_classifier-sandbox_classifierDoNotPutThisStringInFileNameOrWorldWillDiesandbox_classifierDoNotPutThisStringInFileNameOrWorldWillDiesandbox_static_ClassifierSandbox_AppController.h"
@implementation AppController
@end
